import os
from pathlib import Path
from tissue_config import MARKDOWN_DIR, TEMPLATE_DIR, STATIC_DIR

# Create directories
for dir_path in [MARKDOWN_DIR, TEMPLATE_DIR, STATIC_DIR]:
    dir_path.mkdir(parents=True, exist_ok=True)

# Create starter markdown
index_md = MARKDOWN_DIR / "index.md"
if not index_md.exists():
    index_md.write_text("""---
title: Home
desc: Welcome to the site
template: template_default.html
---

# Hello from Tissue!

This page was generated by `tissue.py`.
""", encoding='utf-8')

# Create documentation.md (renderable and usable as project doc)
doc_md = MARKDOWN_DIR / "documentation.md"
if not doc_md.exists():
    doc_md.write_text("""---
title: Documentation
desc: How to use this site generator
template: template_default.html
---

# Documentation

Welcome to **Tissue**, a Python static site generator.

This file serves both as the project documentation *and* a rendered page in the site.

- Files go in `source/`
- Templates in `templates/`
- Static assets in `static/`

Set `exclude: true` in frontmatter to skip a file during navigation or page loops.
""", encoding='utf-8')

# Create starter template
template_default = TEMPLATE_DIR / "template_default.html"
if not template_default.exists():
    template_default.write_text("""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ page.title }}</title>
  <link rel="stylesheet" href="/static/style.css">
</head>
<body>
  <h1>{{ page.title }}</h1>
  <div>{{ page.html|safe }}</div>

  <h2>Other pages:</h2>
  <ul>
  {% for p in root_pages %}
    {% if p.path != page.path %}
      <li><a href="{{ p.path.with_suffix('.html') }}">{{ p.title }}</a></li>
    {% endif %}
  {% endfor %}
  </ul>
</body>
</html>
""", encoding='utf-8')

# Create starter CSS
style_css = STATIC_DIR / "style.css"
if not style_css.exists():
    style_css.write_text("body { font-family: sans-serif; padding: 2rem; }\n", encoding='utf-8')

# Create requirements.txt
Path("requirements.txt").write_text("""markdown
python-frontmatter
jinja2
""", encoding='utf-8')

print("Initialized tissue project structure.")
